### ISSUE TITLE
Check the max input and output length of rgbpp-lock related transaction

### ISSUE THREAD

**Issue by Flouse** [ckb-cell/rgbpp-sdk#108]
## Reason
```rs
struct ExtraCommitmentData {
 input_len: byte,
 output_len: byte,
}
```

## An upper limit check of `rgbppVirtualTx.inputs.length and rgbppVirtualTx.outputs.length` is required
https://github.com/ckb-cell/rgbpp-sdk/blob/da489e554918ca9a576e0319fc369db9ba4a616e/packages/ckb/src/utils/rgbpp.ts#L59

**Comment by duanyytop** [comment]
https://github.com/ckb-cell/rgbpp-sdk/pull/109
