### ISSUE TITLE
refactor: `isMax` -> `shouldCollectAllCells`

### ISSUE THREAD

**Issue by Flouse** [ckb-cell/rgbpp-sdk#116]
Perhaps `isMax` could be evaluated by this way:
If the cell lock is rgbpp-lock, then `isMax` / `shouldCollectAllCells` is true.

_Originally posted by @Flouse in https://github.com/ckb-cell/rgbpp-sdk/pull/67#discussion_r1545042986_

**Comment by duanyytop** [comment]
This issue has been solved in https://github.com/ckb-cell/rgbpp-sdk/pull/113 and I will close it

**Comment by duanyytop** [comment]
https://github.com/ckb-cell/rgbpp-sdk/pull/160
