### ISSUE TITLE
Test failed due to the testnet fee rate fluctuating

### ISSUE THREAD

**Issue by ShookLyngs** [ckb-cell/rgbpp-sdk#117]
Today a [failed test action](https://github.com/ckb-cell/rgbpp-sdk/actions/runs/8671256728/job/23780256848?pr=113#step:9:189) was revealed in the PR #113:
```
 ❯ tests/Transaction.test.ts  (21 tests | 3 failed) 34977ms
   ❯ tests/Transaction.test.ts > Transaction > sendUtxos() > Transfer fixed UTXO, sum(ins) > sum(outs), change = fee + minUtxoSatoshi
     → expected [ { …(3) }, { …(3) } ] to have a length of 1 but got 2
   ❯ tests/Transaction.test.ts > Transaction > sendUtxos() > Transfer fixed UTXO, sum(ins) > sum(outs), change = fee
     → expected [ { …(3) }, { …(3) } ] to have a length of 1 but got 2
   ❯ tests/Transaction.test.ts > Transaction > sendUtxos() > Transfer protected RGBPP_UTXOs, each has free satoshi
     → expected [ { …(3) }, { …(3) } ] to have a length of 1 but got 2
```

The reason the tests failed is because I expected the fee rate on the testnet to always be `1`, so I hardcoded some test cases to ensure the inputs/outputs strictly matched my expectations. 

For example, in one of the failed tests I expected the only input to contain 3000 satoshi, and I expected the only output to contain 1856 satoshi, so then later the SDK should skip the collection process and just create a change output to return change and pay fee.

But such test cases was designed to only work when the fee rate was exactly `1`, so when the Mempool API returned a higher number than this, the test cases failed (with higher fee rate, the inputs may not contain enough satoshi to build the transaction, therefore a collection process is required). An example of querying recommended fee rates via the `https://mempool.space/testnet/api/v1/fees/recommended` API (just for the record, we're currently using the `halfHourFee` in the `develop` branch):
```json
{
  "fastestFee": 8,
  "halfHourFee": 8,
  "hourFee": 8,
  "economyFee": 2,
  "minimumFee": 1
}
```

**Comment by ShookLyngs** [comment]
I think I can resolve this issue by specifying a fixed fee rate in the mentioned test cases. Do you think I should open a PR base on the ` develop` branch, or should it base on the `ref/recommand-fee` branch? @Flouse @duanyytop

**Comment by Flouse** [comment]
> Do you think I should open a PR base on the `develop` branch, or should it base on the `ref/recommand-fee` branch, or else?

1. https://github.com/ckb-cell/rgbpp-sdk/pull/98 needs more discussion and tests.
2. I recommend to fix the tests based on develop branch.
