### ISSUE TITLE
fill the paymaster information automatically

### ISSUE THREAD

**Issue by Flouse** [ckb-cell/rgbpp-sdk#124]
## Requirement
The requirement is to automatically fetch the paymaster information from the BTC Assets API and use it to fill the paymaster-related fields, without requiring manual input from the caller.

## `/rgbpp/v1/paymaster/info` API
https://btc-assets-api.testnet.mibao.pro/docs/static/index.html#/RGB%2B%2B/get_rgbpp_v1_paymaster_info

### Related Code
https://github.com/ckb-cell/rgbpp-sdk/blob/8801c9287f6526fe27d785a8cb3a231417f1766c/packages/btc/src/api/sendRgbppUtxos.ts#L12-L171

**Comment by Flouse** [comment]
### A thought
If a BTC_TX does not have a compliant paymaster output, and the assets-api refuses to process it, users will have difficulty sending the isomorphic CKB transaction on their own.

In this case, I think a better approach for the assets-api would be to record a specific Sentry alert, which should include the `app.domain` information. The maintainer of the `app.domain` should be notified to update their app in order to construct this type of BTC transaction with correct paymaster output.

**Comment by ShookLyngs** [comment]
Should the `paymaster` prop be removed completely (always requesting the paymaster info from the assets-api instead of accepting customizations), or do you think I should simply allow the prop to be optional and fill it from the assets-api?

**Comment by ahonn** [comment]
> In this case, I think a better approach for the assets-api would be to record a specific Sentry alert, which should include the `app.domain` information. The maintainer of the `app.domain` should be notified to update their app in order to construct this type of BTC transaction with correct paymaster output.

When the Paymaster UTXO check is turned on and the transaction does not meet the requirements, the error will be captured in Sentry, but it will not currently contain `app.domain` context (because this is executed in the queue worker without a request context, so this part needs to be passed later through a new RP adds this functionality to Assets API)

**Comment by ahonn** [comment]
> Should the `paymaster` prop be removed completely (always requesting the paymaster info from the assets-api instead of accepting customizations), or do you think I should simply allow the prop to be optional and fill it from the assets-api by default?

I think we could keep the paymaster parameter first and raise an error if it is inconsistent with what the Assets API provides (if checking is enabled).
If the Assets API does not enable checking, then the transaction construction is still performed according to the configured paysmter parameters.
