### ISSUE TITLE
[code-style] Add @typescript-eslint/recommended configuration to the project

### ISSUE THREAD

**Issue by Flouse** [ckb-cell/rgbpp-sdk#131]
## Description
The rgbpp-sdk project currently does not have a comprehensive ESLint configuration set up. To improve code quality and maintainability, I propose adding the @typescript-eslint/recommended configuration to the project.

@ShookLyngs @duanyytop @yuche Do you have a better suggestion?

## Benefits
- Enforces a consistent code style and best practices for this project
- Catches common TypeScript-specific errors and potential issues early in the development process
- Improves code maintainability and readability

**Comment by ShookLyngs** [comment]
One concern is that, while we're currently using prettier for code formatting only, it's because prettier doesn't introduce too many dependencies or steps. In my experience, there would be some work to be done in order to stop the conflicts between prettier and eslint. This would require additional dependencies and configurations.

Are there any new tools on the marketplace that can save us some effort?

**Comment by ahonn** [comment]
> One concern is that, while we're currently using prettier for code formatting only, it's because prettier doesn't introduce too many dependencies or steps. In my experience, there would be some work to be done in order to stop the conflicts between prettier and eslint. This would require additional dependencies and configurations.
> 
> Are there any new tools on the marketplace that can save us some effort?

May we consider using [biome](https://biomejs.dev/).

**Comment by duanyytop** [comment]
I agree to use @typescript-eslint/recommended to improve code quality and I think the cost of resolving the conflict is acceptable

**Comment by yuche** [comment]
I don't think [biome](https://biomejs.dev/) or [oxc-linter](https://oxc-project.github.io/docs/guide/usage/linter.html) are a good choice. They all have the same main problems:

1. the project is too young
2. too few rules are supported
3. they don't have wide editor support and mature editor plugins, e.g. I'm a vim/zed user and I can't use them.

ESLint is a safer and more mature choice, the ecosystem is rich and well-tested. prettier can coexist with ESLint, just use [eslint-config-preitter](https://github.com/prettier/eslint-config-prettier) and [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier). And prettier and ESLint solve different problems, one of them is formatter and the other one is linter, formatter solves the problem of code style, linter solves the problem of best practice. 

The more crucial issue is what rules we should use. Besides `@typescript-eslint/recommended` and `eslint/recommended`, a widely used and recognized rule in the community is the [Airbnb Style Guide](https://github.com/airbnb/javascript) / [eslint-config-airbnb](https://github.com/iamturns/eslint-config-airbnb-typescript), but if we use the airbnb linter rules, there may be a large number of code changes that need to be made.

**Comment by ahonn** [comment]
The experience of using eslint + prettier is not bad. Referring to the config in the Assets API project, adding simple-git-hooks and lint-staged can guarantee the code style of the committed code.
We can consider using these mature tool chains first, and then replacing them if necessary.

> Besides @typescript-eslint/recommended and eslint/recommended, a widely used and recognized rule in the community is the [Airbnb Style Guide](https://github.com/airbnb/javascript) / [eslint-config-airbnb](https://github.com/iamturns/eslint-config-airbnb-typescript), but if we use the airbnb linter rules, there may be a large number of code changes that need to be made.

I think @typescript-eslint/recommended and eslint/recommended is enough

**Comment by duanyytop** [comment]
Examples eslint: https://github.com/ckb-cell/rgbpp-sdk/pull/147
