### ISSUE TITLE
Support BTC signet

### ISSUE THREAD

**Issue by ShookLyngs** [ckb-cell/rgbpp-sdk#170]
## Background

The BTC testnet3 is currently slow and the peak fee rate is sky high.
Therefore, we may have to support switching to other testnets in the rgbpp-sdk/btc.

## Questions

Some questions to be answered, some decisions to be made:

1. Which network should we support: testnet4 or signet?
    1. What's the difference between these two networks?
    2. Will testnet4 become the default testnet in the future?
2. Should the new testnet replace the `NetworkType.TESTNET`, or should we add a new `NetworkType` option?
    1. If adding an option, how should we handle them when testnet4 becomes the default testnet?

## Discussion -> Conclusions
1. [BTC testnet4](https://github.com/bitcoin/bitcoin/pull/29775) is not finalized yet, so BTC signet will be supported first. BTC testnet4 may be supported later.

2. The BTC testnet3 should continue to be maintained as most of the RGB++ testnet dApps are running on this environment. A new `BTC NetworkType` may be required to accommodate this need.

### Bitcoin/RGB++ Assets API @ahonn @mfuuzy
- [x] deploy a BTC signet node + btc-rpc-proxy + electrs
  - [x] test [mempool signet](https://mempool.space/signet) API
- [x] assets-api for BTC signet + CKB testnet 
  https://api.signet.rgbpp.io/docs

### BTC signet SPV on CKB testnet @EthanYuan 
- [x] deploy a new instance of BTC signet SPV on CKB testnet
  https://pudge.explorer.nervos.org/script/0xc8a30fe3e8101cb4163e70b4eb1e42d477ae7094524a30bfdf1c90be41876d28/type
- [x] btc-spv-service updater and watcher
- [x] https://github.com/ckb-cell/ckb-bitcoin-spv/pull/19

### CKB testnet rgbpp contracts with BTC signet SPV config @EthanYuan @jjyr 
- [x] rgbpp-lock deployment: https://pudge.explorer.nervos.org/transaction/0x61efdeddbaa0bb4132c0eb174b3e8002ff5ec430f61ba46f30768d683c516eec
- [x] btc-time-lock deployment: https://pudge.explorer.nervos.org/transaction/0x5364b3535965e9eac9a35dd7af8e9e45a61d30a16e115923c032f80b28783e21

### rgbpp-sdk/btc @ShookLyngs 

Without modification:
- [x] Test basic transfer with P2WPKH/P2TR accounts

If adding NetworkType.SIGNET:
- [ ] Update the [`decodeAddress`](https://github.com/ckb-cell/rgbpp-sdk/blob/develop/packages/btc/src/address.ts#L117-L202) function and remove the `networkType` from the return type, as it's no longer accurate
- [ ] Check and update where the `decodeAddress` function was referenced

> [!NOTE]
> need discussion because signet and testnet are almost exactly the same at the application level
  ref: https://github.com/bitcoinjs/bitcoinjs-lib/issues/1820#issuecomment-1166672693

### rgbpp-sdk/ckb @duanyytop 
- [x] Add Signet RGB++ lock script and BTC time lock script
- [x] Support all RGB++ operations for BTC Signet network
- [x] Update all RGB++ examples to support BTC Signet network
- [x] Tests: adjust tests to use the new network @duanyytop @Dawn-githup 

## References
- https://pudge.explorer.nervos.org/ will https://github.com/Magickbase/ckb-explorer-public-issues/issues/700

**Comment by Dawn-githup** [comment]
### You can currently claim sBTC test coins through 2 faucets

Faucet 1: https://signetfaucet.com/ (0.00001 at a time)

Faucet 2: https://botanix.5thweb.io/ (0.001 at a time, 1 time in 24 hours)

**Comment by duanyytop** [comment]
If we switch to BTC testnet4, do we redeploy RGB++ lock script and BTC time lock script for testnet4?
If yes, we will update `rgbpp-sdk/ckb`.

**Comment by Flouse** [comment]
Since BTC testnet3 is coming back somehow. So the priority of supporting BTC signet or testnet4 is now lower.

> If we switch to BTC testnet4, do we redeploy RGB++ lock script and BTC time lock script for testnet4?
> If yes, we still need to update `rgbpp-sdk/ckb`.

However, if testnet3 remains unstable or problematic, then rgbpp-sdk and assets-api have to investigate to support a new test environment. So the answer to your question is `Yes`, in a long term.

**Comment by Flouse** [comment]
### tracking
- https://pudge.explorer.nervos.org/ will https://github.com/Magickbase/ckb-explorer-public-issues/issues/700
