### ISSUE TITLE
test: Update the rgbpp-sdk version used in examples to v0.3.0

### ISSUE THREAD

**Issue by Flouse** [ckb-cell/rgbpp-sdk#196]
## Search
https://github.com/search?q=repo%3Ackb-cell%2Frgbpp-sdk+0.1.0&type=code

## References
- https://github.com/ckb-cell/rgbpp-sdk/releases/tag/v0.3.0
- #194 
- #195 
- https://github.com/ckb-cell/rgbpp-sdk/releases
- https://www.npmjs.com/package/rgbpp/v/0.2.0

**Comment by Dawn-githup** [comment]
https://github.com/ckb-cell/rgbpp-sdk/pull/220
