### ISSUE TITLE
potential scenario: one rgbpp_lock <-> muti UDT types

### ISSUE THREAD

**Issue by Flouse** [ckb-cell/rgbpp-sdk#23]
### A potential scenario
The same "RGB++ lock" may correspond to multiple types of User Defined Types (UDT).

All the rgbpp asset cells that are isomorphic with a specific BTC_UTXO, **should be unlocked in one single transaction.**

## Related Code Blocks
- https://github.com/ckb-cell/rgbpp-sdk/blob/5a1408d0699f3556b971a9782a9feef3ea66b4f8/packages/ckb/src/rgbpp/btc-jump-ckb.ts#L30-L36
- https://github.com/ckb-cell/rgbpp-sdk/blob/9e9a055800995ccbf6281fc91afb77951e2ce944/packages/ckb/src/rgbpp/btc-transfer.ts#L29-L30
- https://github.com/ckb-cell/rgbpp-sdk/blob/ed8b0f26f87d02cbdccd8fcad3ec484dd55e80e4/packages/ckb/src/rgbpp/btc-transfer.ts#L199-L207
- Search
  https://github.com/search?q=repo%3Ackb-cell%2Frgbpp-sdk+%22collector.getCells%28%7B+lock%3A+rgbppLock%22&type=code

## Related issues
- https://github.com/ckb-cell/rgbpp-sdk/issues/66

**Comment by duanyytop** [comment]
```
ckb tx: 

{
	inputs: [
		targetRgbppCellInput,   // BTC UTXO1
		otherRgbppCellInput1,   // BTC UTXO1
		otherRgbppCellInput2,   // BTC UTXO1
	],
	outputs: [
		targetRgbppCellTransferOutput,     // BTC UTXO2
		targetRgbppCellChangeOutput,       // BTC UTXO3 (optional)
		otherRgbppCellOutput1,             // BTC UTXO4
		otherRgbppCellOutput2,             // BTC UTXO5
	]	
}


btc tx:

ins
- UTXO1
- BTC UTXO for fee
outs:
- UTXO2
- UTXO3   // optional
- UTXO4
- UTXO5
- BTC UTXO as change
```

**Comment by duanyytop** [comment]
Our original conclusion was to return all non-target RGB++ assets to a new sender UTXO. After communicating with @ShookLyngs, he suggested allocating a sender UXTO to each non-target RGB++ asset. 

The advantage of this is that each of the non-target RGB++ assets can be allocated to one sender UTXO in one transaction. In other word, the RGB++ assets are separated in one transaction.

The disadvantage is that the cost is relatively high.

@Flouse @CipherWang

**Comment by CipherWang** [comment]
Maybe there is a better solution with the balance of cost efficiency and user experience. If we can differentiate every UTXO with RGB++ assets from non-RGB++ assets UTXO in the wallet level, we actually don't need to rely on the Satoshi amount in UTXO to detect the RGB++ assets. Which means, we can attach the RGB++ assets to any UTXO, including the change ones. 

So for the assets to be sent to others, the sender generate a dust UTXO for the receiver to attach the assets. For the assets to be seperated from a multi-assets-binded UTXO, we simply attach the rest assets, no matter how many of them, to the change utxo. Here follows an example:

```
ins
- UTXO1      # lock for asset1, asset2, asset3, ...
- BTC UTXO for fee
outs:
- UTXO2      # utxo for the receiver, lock for asset1
- UTXO3      # change utxo, also act as the lock for asset2, asset3, ...
```

**Comment by duanyytop** [comment]
It's OK for the CKB package and the complexity has not increased, but it may increase some complexity for the BTC package. What do you think about that? @ShookLyngs

**Comment by ShookLyngs** [comment]
## Attach RGBPP assets to any UTXO

> Which means, we can attach the RGB++ assets to any UTXO, including the change ones.

I feel like the "splitting" feature is needed, because:

- When a user wants to spend the satoshi within a RGBPP UTXO (if it isn't a dust), a "splitting" action is still needed
- Users may have to be careful about which wallet NOT to use, because non-dust UTXOs are easily spent

## The options of "splitting"

Let's review our options:

1. Each RgbppLock Cell attach to a standalone dust UTXO:
    - Transactions are easy to write and read, rules are relatively simple
    - Cost more satoshi when splitting, each Rgbpp Cell attach to a standalone dust UTXO
2. Merge as much types of RgbppLock Cells to one UTXO as possible:
    - Cost less satoshi becuase each "splitting" generates less UTXOs
    - Complexity increased, need to be careful when generating transactions

As to which option is better, I'll say if we wish to start simple, option 1 is more suitable as it requires fewer changes in both code and rules. But it really depends on how we feel about merging/splitting different types of RGBPP assets.

## The options of "merging"

Option 2 is actually the combination of splitting and merging, both actions happening in one transaction. Despite the fact that I don't quite enjoy merging assets together because it complicates the rules/design of transaction generation, somehow I feel like "merging assets" is a needed feature that we may just need to provide as an option.

To start, here's an example of the option 2 outcome:

```
[ckb tx]
inputs:
- RgbppLock Cell1, type=A, amount=100, attached=UTXO1
- RgbppLock Cell2, type=B, amount=100, attached=UTXO1
outputs:
- RgbppLock Cell2, type=A, amount=60, attached=UTXO3
- RgbppLock Cell3, type=A, amount=40, attached=UTXO4
- RgbppLock Cell4, type=B, amount=100, attached=UTXO4

[btc tx]
ins:
- Rgbpp UTXO1, value=546, address=Alice
- Btc UTXO2, value=2000, address=Alice
outs:
- Rgbpp UTXO3, value=546, address=Bob
- Rgbpp UTXO4, value=546, address=Alice
- Btc UTXO5, value=1000, address=Alice
```


### Accept a boolean

If the option is `true`, we can group outputs by address if the output will be attached to any RGBPP assets:

```ts
sendRgbppUtxos({
  ...
  mergeRgbppOutputsByAddress: true,
});
```

### Accept a function

We may accept a function that decides which outputs should be merged/grouped together:

```ts
sendRgbppUtxos({
  ...
  mergeRgbppOutputs: (a: Output, b: Output) => {
    return isSameAddress(a, b);
  },
});
```

**Comment by Flouse** [comment]
### My opinion

1. To improve the transaction readability, the rgbpp-sdk should only help bind rgbpp assets to dust BTC UTXOs (546 sats). This will prevent misuse of rgbpp assets by other wallets as well.

2. Whether to create one-to-one relationship between `one rgbpp_lock <-> one UDT type`, it depends on the wallet or dApp's choice.  I think Shook has provided a function option that allows the wallet/dApp to have a choice. Because sometimes a user just doesn't have enough BTC to achieve the one-to-one relationship.

**Comment by duanyytop** [comment]
The dApps and wallets will not know so many details. In most cases, they will only use the practices recommended by the SDK, and different options have different requirements for UI/UX. I think we should only keep `mergeRgbppOutputsByAddress`. 

Less is more.

**Comment by ahonn** [comment]
I think default merging may bring more complexity in the future, and keeping one Cell corresponding to one UTXO is more scalable.
Split when multiple assets are bound to the same UTXO. We only need to add this rule. Otherwise, we need to consider whether to merge in various situations.

**Comment by duanyytop** [comment]
```
[ckb tx]
inputs:
- RgbppLock Input1, type=A, amount=100, attached=UTXO1
- RgbppLock Input2, type=B, amount=100, attached=UTXO1
- RgbppLock Input3, type=C, amount=100, attached=UTXO1
outputs:
- RgbppLock Output1, type=A, amount=60, attached=UTXO3
- RgbppLock Output2, type=A, amount=40, attached=UTXO4
- RgbppLock Output3, type=B, amount=100, attached=UTXO5
- RgbppLock Output3, type=B, amount=100, attached=UTXO6

[btc tx]
ins:
- Rgbpp UTXO1, value=546, address=Alice
- Btc UTXO2, value=2000, address=Alice
outs:
- OpReturn UTXO, data=commitment
- Rgbpp UTXO3, value=546, address=Bob
- Rgbpp UTXO4, value=546, address=Alice
- Rgbpp UTXO5, value=546, address=Alice
- Rgbpp UTXO6, value=546, address=Alice
- Btc UTXO7, value=1000, address=Alice
```

**Comment by duanyytop** [comment]
Related PR: https://github.com/ckb-cell/rgbpp-sdk/pull/139
