### ISSUE TITLE
Fix `Docker Publish` workflow

### ISSUE THREAD

**Issue by Flouse** [ckb-cell/rgbpp-sdk#282]
https://github.com/ckb-cell/rgbpp-sdk/actions/runs/10397406203 was failed since PR278.

## References
- https://github.com/ckb-cell/rgbpp-sdk/pull/278

**Comment by duanyytop** [comment]
I'm just wondering: Is the Docker Image for the SDK Service necessary? 

Likely, CoinEx doesn't use it, and Docker isn't needed in daily development. I suggest we remove Docker.

**Comment by Flouse** [comment]
> Docker isn't needed in daily development

You may be right.
We can disable [the workflow](https://github.com/ckb-cell/rgbpp-sdk/pkgs/container/rgbpp-sdk-service) for now.
