### ISSUE TITLE
Unlock/Spent all the cells of a rgbpp-lock at one time

### ISSUE THREAD

**Issue by Flouse** [ckb-cell/rgbpp-sdk#66]
https://github.com/ckb-cell/rgbpp-sdk/blob/92021373373a45497a48379a5828b4f2baabf4d8/packages/ckb/src/collector/index.ts#L117-L130

## L128
If a rgbpp-lock owns many cells, they should be unlocked/spent at one time.
Or the left cells can be locked forever.

**Comment by duanyytop** [comment]
https://github.com/ckb-cell/rgbpp-sdk/pull/67
