### ISSUE TITLE
Refactor the default feeRate of rgbpp-sdk/btc

### ISSUE THREAD

**Issue by Flouse** [ckb-cell/rgbpp-sdk#92]
Tune the default fee_rate of a btc transaction to the `fastestFee` of `curl -sSL "https://mempool.space/api/v1/fees/recommended"`.

## Related Code
https://github.com/ckb-cell/rgbpp-sdk/blob/44b8eda57b5a51a0a7b9a0ebd181b19d5e8db2c6/packages/btc/src/query/source.ts#L153-L161

https://github.com/ckb-cell/rgbpp-sdk/blob/44b8eda57b5a51a0a7b9a0ebd181b19d5e8db2c6/examples/rgbpp/local/transfer-btc.ts#L34-L35

**Comment by ShookLyngs** [comment]
Two questions:
1. Do you wish all APIs to use the `fastestFee`?
2. Do you prefer an option (e.g. `recommendedFeeType`) to adjust the fee rate?

**Comment by Flouse** [comment]
> * Do you wish all APIs to use the `fastestFee`?

1. Yes, use mempool.space API's `fastestFee` by default if the param `feeRate` is not specified.

> * Do you prefer an option (e.g. `feeType`, `recommendedFeeType`) to adjust the fee rate?

2. LGTM. Do you mean supports `feeType: number | recommendedFeeType`?

**Comment by ShookLyngs** [comment]
> 2. LGTM. Do you mean supports `feeType: number | recommendedFeeType`?

I was thinking maybe we can add a prop in the APIs (feeType or recommendedFeeType):
```
sendBtc({
  ...
  feeRate: 1, // optional, default to undefined
  feeType: 'halfHourFee', // optional, if "feeRate == undefined", use FeesRecommended[feeRate] as the fee rate
});
```
