### ISSUE TITLE
The CKB tx outputs will be removed

### ISSUE THREAD

**Issue by duanyytop** [ckb-cell/rgbpp-sdk#97]
https://github.com/ckb-cell/rgbpp-sdk/blob/develop/packages/ckb/src/rgbpp/ckb-builder.ts#L165

A bug in the above code will delete outputs except for RGBPP lock and BTC time lock. Since these two output cells are used in all scenarios, there is no problem for now, but there is indeed a problem here.

**Comment by ShookLyngs** [comment]
Do you think it should be fixed before the main release? 
```ts
const outputs = ckbRawTx.outputs
  .map((output) => {
    if (!isRgbppLockOrBtcTimeLock(output.lock, isMainnet)) {
      return output;
    }
    return {
      ...output,
      lock: {
        ...output.lock,
        args: replaceLockArgsWithRealBtcTxId(output.lock.args, btcTxId),
      },
    };
  });
```

**Comment by duanyytop** [comment]
https://github.com/ckb-cell/rgbpp-sdk/pull/107
